---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-iptables-tailer
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: kube-iptables-tailer
  template:
    metadata:
      labels:
        app: kube-iptables-tailer
    spec:
      serviceAccountName: kube-iptables-tailer
      containers:
        - name: kube-iptables-tailer
          image: boxinc/kube-iptables-tailer:v0.1.0
          command:
            - /kube-iptables-tailer
          args:
            - --log-driver=journalctl
            - --log-prefix=calico-drop
          env:
            - name: LOG_LEVEL
              value: info
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-iptables-tailer
  namespace: kube-system

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-iptables-tailer
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["v1"]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-iptables-tailer
subjects:
  - kind: ServiceAccount
    name: kube-iptables-tailer
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kube-iptables-tailer
  apiGroup: rbac.authorization.k8s.io